"""Locked gene sets. CLDN4 is the readout. No dual-high gate.

Barrier/keratin excludes CLDN4. IFN is Hallmark IFNα (CLDN4 is not in the set).
TACSTD2 is a comparator only.
"""

from __future__ import annotations

STATES = {
    "AT2": ("SFTPC", "SFTPB", "SFTPA1", "NAPSA", "LAMP3", "ABCA3"),
    "AT1": ("AGER", "PDPN", "CAV1"),
    "club": ("SCGB1A1", "SCGB3A2", "SCGB3A1"),
    "basal": ("KRT5", "KRT15", "TP63", "NGFR"),
    "ciliated": ("FOXJ1", "TPPP3", "PIFO"),
    # CLDN4 excluded on purpose.
    "barrier_keratin": (
        "KRT8",
        "KRT18",
        "KRT19",
        "KRT7",
        "CDKN1A",
        "PLAUR",
    ),
    "malignant_like": ("CEACAM5", "CEACAM6", "MKI67"),
    # Compact ISG/MHC-I panel (CLDN4 not a member). Extra to Hallmark IFNα.
    "ifn_isg": (
        "STAT1",
        "IRF1",
        "IRF7",
        "IRF9",
        "ISG15",
        "MX1",
        "OAS1",
        "IFI27",
        "IFI44",
        "IFI44L",
        "IFIT1",
        "IFIT2",
        "IFIT3",
        "CXCL10",
        "B2M",
        "HLA-A",
        "HLA-B",
        "HLA-C",
        "PSMB8",
        "PSMB9",
        "TAP1",
    ),
}

# Hallmark interferon-alpha response (Liberzon Cell Syst 2015 / MSigDB).
# Same family used in the pair malignant IFN DE (PR #469). CLDN4 is not in this set.
HALLMARK_INTERFERON_ALPHA_RESPONSE = (
    "ADAR",
    "B2M",
    "BATF2",
    "BST2",
    "C1S",
    "CASP1",
    "CASP8",
    "CCRL2",
    "CD47",
    "CD74",
    "CMPK2",
    "CMTR1",
    "CNP",
    "CSF1",
    "CXCL10",
    "CXCL11",
    "DDX60",
    "DHX58",
    "EIF2AK2",
    "ELF1",
    "EPSTI1",
    "GBP2",
    "GBP4",
    "GMPR",
    "HELZ2",
    "HERC6",
    "HLA-C",
    "IFI27",
    "IFI30",
    "IFI35",
    "IFI44",
    "IFI44L",
    "IFIH1",
    "IFIT2",
    "IFIT3",
    "IFITM1",
    "IFITM2",
    "IFITM3",
    "IL15",
    "IL4R",
    "IL7",
    "IRF1",
    "IRF2",
    "IRF7",
    "IRF9",
    "ISG15",
    "ISG20",
    "LAMP3",
    "LAP3",
    "LGALS3BP",
    "LPAR6",
    "LY6E",
    "MOV10",
    "MVB12A",
    "MX1",
    "NCOA7",
    "NMI",
    "NUB1",
    "OAS1",
    "OASL",
    "OGFR",
    "PARP12",
    "PARP14",
    "PARP9",
    "PLSCR1",
    "PNPT1",
    "PROCR",
    "PSMA3",
    "PSMB8",
    "PSMB9",
    "PSME1",
    "PSME2",
    "RIPK2",
    "RNF31",
    "RSAD2",
    "RTP4",
    "SAMD9",
    "SAMD9L",
    "SELL",
    "SLC25A28",
    "SP110",
    "STAT2",
    "TAP1",
    "TDRD7",
    "TENT5A",
    "TMEM140",
    "TRAFD1",
    "TRIM14",
    "TRIM21",
    "TRIM25",
    "TRIM26",
    "TRIM5",
    "TXNIP",
    "UBA7",
    "UBE2L6",
    "USP18",
    "WARS1",
)

FOCAL = ("CLDN4",)
COMPARATOR = ("TACSTD2",)
CONTROLS = ("SFTPC", "KRT8", "SCGB1A1", "KRT5", "EPCAM", "PTPRC")
QC_NEG = ("PTPRC", "PECAM1", "COL1A1")

EPI_GATE = ("EPCAM", "KRT8", "KRT18", "KRT19")
