name: scrna_harmony_neoadj
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - openpyxl
  - pip
  - pip:
      - harmonypy
      - umap-learn
      - igraph
      - leidenalg
      - statsmodels
